
// Crear un usuario
POST /api/users/ HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "username": "john_doe"
}

// Verificar el usuario creado
GET /api/users/john_doe HTTP/1.1
Host: localhost:8080

// Eliminar un usuario
DELETE /api/users/lalachip HTTP/1.1
Host: localhost:8080

// Cambiar el nombre de usuario
PUT /api/users/john_doe HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "newUser": "johnsmith"
}   

// Comprobar usuarios conectados
GET /api/status/connected-users HTTP/1.1
Host: localhost:8080




// Crear una partida
POST /api/games/ HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "usernamePlayer1": "john_doe",      
    "usernamePlayer2": "marta_sainz",    
    "map": 1,               
    "player1": 2,        
    "player2": 4,      
    "code": 1       
}

// Verificar el usuario creado
GET /api/games/1 HTTP/1.1
Host: localhost:8080

// Eliminar un usuario
DELETE /api/games/1 HTTP/1.1
Host: localhost:8080

// Cambiar el nombre de usuario
PUT /api/users/john_doe HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "newUser": "johnsmith"
}   
